name: CyberEnte-Extended
version: '1.0.0-SNAPSHOT'

main: de.datenente.cyberente.extended.CyberEnteExtended
api-version: '1.21'

website: https://www.e-duck.de
description:  Ein maßgeschneidertes Minecraft Paper-Plugin für den privaten CyberEnte-Server. Der Bibliotheken für das Minecraft Paper-Plugin CyberEnte enthält, die für den Betrieb des Plugins erforderlich sind.
authors: [CyberEnte, KeksGauner]