name: CI Code Quality Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Check code quality
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Shadow Jar
        run: ./gradlew shadowJar --refresh-dependencies

      - name: Spotless Check
        run: ./gradlew spotlessCheck
